### ISSUE TITLE
error calculating days in month

### ISSUE THREAD

**Issue by igor1980** [kthornbloom/Monthly#1]
When change month there's an error calculating dayQty variable with function daysInMonth, correct calling is 

var dayQty = daysInMonth(m, y)

current calling is 

var dayQty = daysInMonth(currentMonth, currentYear)

so number of total days of any month is the same of current month.

thanks for

best regards
Igor

**Comment by kthornbloom** [comment]
Oops! Thank you. I've updated this and credited you in the readme file.
