### ISSUE TITLE
How to reload events when I changet XML

### ISSUE THREAD

**Issue by OndrejL81** [kthornbloom/Monthly#12]
Hi im am trying make different events, but if I change events.xml and I refresh browser, then nothing change.
If i delete some event, it steel appear in calendar. No refresh helps. Even if I reopen browser (mozilla)

So how can I refresh the calendar, when I change event.xml?

Thanks

**Comment by kthornbloom** [comment]
Hm, are you sure you are changing the correct xml? I've not run into any issue like this in my testing. If you'd like to share a URL, and what event you changed, I can let you know if I am seeing the updated version on my end.

**Comment by OndrejL81** [comment]
Hi,
thank you for answer. Here is the link http://www.sakba.sk/calendar/

there is also a link tu event.xml
but it never change. even if you make new event. But 100% it change on server. I can proof it vie FTP. everithing change, ID and XML

but browser has steel the same old XML.

**Comment by OndrejL81** [comment]
Hi, 

it was exactly how I wrote. Browser download xml only once and hold it. Even if xml was changed.
very simple solution is make a random variable after events.xml
and it works. that it 

	$(window).load( function() {
		$('#mycalendar').monthly({
			mode: 'event',
			xmlUrl: 'events.xml?rnd='+Math.random()
		});

**Comment by kthornbloom** [comment]
Looks like a good solution! Glad you got it sorted out. I may make a note of this in the documentation.

**Comment by OndrejL81** [comment]
Yes,
and maybe it should better to make timestamp expect random number
