### ISSUE TITLE
All event disapear after a click on an event in day-mode

### ISSUE THREAD

**Issue by pieropingi** [kthornbloom/Monthly#15]
I click on the 'today' case. It enters in what I call 'day-mode'. No events today.
I go in the past (top-left arrow). The previous month (march 2016) event list is displayed.
I click on an event. Nothing happens.
From now on, if I change month, no events are displayed, even in the months where events exists. I have to reload the entire page to unblock it.
Attention: this happens in the demo at this address: http://www.jqueryrain.com/?V0HmbSvH
In the demo at the other address (http://kthornbloom.com/monthly/) that doesn't happens because when I click an event, it goes on google start page, so I have to reload the calendar page to see it again and the error is cleared.
Hope you can understand my bad english.

**Comment by pieropingi** [comment]
sorry: chrome I forgot: Chrome Versione 49.0.2623.110 m on PC

**Comment by pieropingi** [comment]
The issue have somthing to do with the jQueryRain topbar. That impeach the google link to work and probably cause the problem. If i close the topbar (top-right red button), no error arise.

**Comment by kthornbloom** [comment]
Glad you have it sorted out. I'll close this since the issue doesn't seem to be with the plugin
