### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by jbub561** [kthornbloom/Monthly#18]
Everything works and then when i put in the url link all items on calendar dissapear

**Comment by kthornbloom** [comment]
Hi, can I ask what the URL is? I wonder if there is some special character which is causing an error. 

Also, have you checked console for any error messages?

**Comment by jbub561** [comment]
Ive tried several urls. Even simply google.com.  using http://,www,
http://www and even /calendar.html. etc. And when i upload the events.xml
all the calendar goes blank all events fall off

**Comment by kthornbloom** [comment]
Hm. Must be something else because URLs are working well in the demo: http://kthornbloom.com/monthly/

• Are you getting any console errors?
• Have you tried a really simple XML setup like the following?

```
<?xml version="1.0"?>
<monthly>

	<event>
		<id>1</id>
		<name>Event Name 1</name>
		<startdate>2016-4-1</startdate>
		<enddate></enddate>
		<starttime>9:00</starttime>
		<endtime>10:00</endtime>
		<color>#ffb128</color>
		<url>http://www.google.com</url>
	</event>

</monthly>
```
