### ISSUE TITLE
There is a problem with multiple events and another problem with month forward and backward

### ISSUE THREAD

**Issue by TGilany** [kthornbloom/Monthly#19]
When I have multiple events on a certain day the calendar stretches in order to show all of them instead showing a scroll par or something else.

![untitled](https://cloud.githubusercontent.com/assets/9105484/14833514/61abb438-0c08-11e6-91e9-8d6855de966c.png)

Another problem is that when I click next month or previous it keeps generating <div class="monthly-week"></div>
and doesn't remove the old ones.

![untitled](https://cloud.githubusercontent.com/assets/9105484/14833607/cce598ea-0c08-11e6-9b58-8a9c7f26c786.png)

I did a temporary fix for this but would appreciate if you guys will fix this.

**Comment by kthornbloom** [comment]
Thanks for the report! I've fixed those extra divs getting left behind. As far as the events, find .monthly-indicator-wrap in the CSS. You can add max-height and overflow:auto to get the behavior you're after.
