### ISSUE TITLE
Days and dates Different in some browsers

### ISSUE THREAD

**Issue by offtrolley** [kthornbloom/Monthly#2]
Minor issue viewing your demo, there are differences between days and dates.
IE 11 shows Jan 1st as Sunday
Chrome shows Jan 1st as Friday
Firefox shows Jan 1st as Friday (but squeezes the height)
Safari just screws it up all together

Still, it's the best looking calendar I've tried. Congrats on the new code and hope to see it develop further.
Rob

**Comment by kthornbloom** [comment]
Hey Rob, thanks for letting me know. I'm just starting to get this plugin off the ground, and haven't used it in any production work yet, so I really appreciate the bug notices. I'll take a look at those differences soon.

**Comment by kthornbloom** [comment]
Ok, check out v 2.0.1 for fixes. I've also updated the demo (though it may need a refresh on your end). Let me know if you run into anything else!
