### ISSUE TITLE
close button

### ISSUE THREAD

**Issue by shivanitak157** [kthornbloom/Monthly#25]
no close button

**Comment by vangoo** [comment]
change 
`<div class="monthly-event-list"></div>`
with 
`<div class="monthly-event-list" onclick="closeEvent()"></div>`
and add this

```
function closeEvent(){
            jQuery('.monthly-event-list').hide();
        }

```

Have Fun

**Comment by kthornbloom** [comment]
There actually is one, (a little month icon) but it wasn't highly visible. Updates coming soon for that!
