### ISSUE TITLE
Start date for calendar

### ISSUE THREAD

**Issue by jledfordtbc** [kthornbloom/Monthly#26]
I don't know if this is a code issue or my issue but this is the only place I see to submit a question.  I am trying to get this calendar to start on the first day it has events and don't readily see where to do that.  For example, the events.xml file I am loading doesn't have events until 3 months after today.  The calendar loads the current month and I have to scroll through blank months to get to where my events are loaded.  Does this functionality exist or what am I missing?  Thanks.

**Comment by kthornbloom** [comment]
Hey there. The short answer is that it doesn't have that capability. This plugin was built with simplicity in mind rather than tons of features & options. You might check out http://fullcalendar.io to see if it would be a better fit for you!

**Comment by jledfordtbc** [comment]
I did check it out but honestly I have had much better luck with this plugin.  Thanks for the help.
