### ISSUE TITLE
event calendar does not work on mobile platform

### ISSUE THREAD

**Issue by jtmager** [kthornbloom/Monthly#3]
Hi,

thanks for this nice eventcalendar.
are you also going to get it to work on mobile browsers (chrome, safari, etc..)?
at the moment, it's not possible to use it in one of these browsers.

thanks

**Comment by kthornbloom** [comment]
Hi, I have limited devices to test with, however Chrome on Android 5.1 seems to be running it normally. Can you give specifics about what you are using, and what's not working?

**Comment by jtmager** [comment]
hi,
wow, you're fast ;-)

i have tested on an iPad mini (version 1).
both Chrome and safari just mess up the entire calendar.

**Comment by kthornbloom** [comment]
Thanks for the screenshot. I'm surprised it would break that much! I used to have that exact device until I left it on the roof of my car one day. :) Just to confirm, does the calendar on the demo page break for you as well? http://kthornbloom.com/monthly Are you browsers up to date?

**Comment by jtmager** [comment]
yes, the calendar on the demo-page breaks as well. (the same way)
both browsers are up to date.

i also tried my iphone4.... with same result

**Comment by kthornbloom** [comment]
Hmm. What version of iOS are you running? I'm testing using 9.2 using the xcode simulator and it seems to be working normally.

**Comment by jtmager** [comment]
I'm running 8.1.2 
I noticed that it looks ok in the iOS simulator.

I'll ask a vriend wiith an iPad with latent iOS to test

**Comment by jtmager** [comment]
I am running iOS 8.1.2 on my iPad with Chrome 48.0.xxxxxx

**Comment by kthornbloom** [comment]
Thanks for the help with the testing. I wish there was a way to test previous versions of iOS without one of those devices.

**Comment by jtmager** [comment]
No problem, understand your problem. let me know if i can help!

**Comment by vritzka** [comment]
Hi, thanks for the calender plugin! 

You could use Browserstack to test older IOS versions.

**Comment by kthornbloom** [comment]
Should be fixed in the most recent update. The only thing changed was adding some vendor specific prefixes to the CSS!

**Comment by jtmager** [comment]
Works like a Charm!!! thanks!
