### ISSUE TITLE
Can't seem to get my events to load

### ISSUE THREAD

**Issue by LinkBenjamin** [kthornbloom/Monthly#32]
Hi.  Loved the example and it fits precisely with what I'm trying to do in my webapp.  The problem I'm having is that I can't get my file to load events in.

I've got a restful-type call made that returns json data (example here:
**[{"id":97,"name":"certificatename","startdate":1475614800000,"enddate":1475616600000,"starttime":1475614800000,"endtime":1475616600000,"color":"#0000FF","url":"/library/detail/922"}]**

I see that my api call is working fine, and I get no errors when I try to load it up, but the following js doesn't work:

HTML:
```
<div style="width:100%; max-width:600px; display:inline-block;">
	<div class="monthly" id="mycalendar"></div>
</div>
```	

JS:
```
$(window).load( function() {

		$('#mycalendar').monthly({
			mode: 'event',
			jsonUrl: '/api/public/eventcalendar',
			dataType: 'json'
		});
	
	});
```

When I do this, my calendar object loads up fine but there are no events populated.  What did I miss?

**Comment by LinkBenjamin** [comment]
As a note... I used the included example json file as a guide, and I did try formatting the dates & times as strings rather than passing in the long value.

**Comment by keegars** [comment]
Hey there, 
I see two problems with your code. 

Firstly your api json, should be wrapped by a monthly object such as: 
'
{
  "monthly": [
    {
      "id": 1,
      "name": "This is a JSON event",
      "startdate": "2016-9-15",
      "enddate": "2016-9-18",
      "starttime": "12:00",
      "endtime": "2:00",
      "color": "#FFB128",
      "url": ""
    },
    {
      "id": 2,
      "name": "This is a JSON event",
      "startdate": "2016-10-15",
      "enddate": "",
      "starttime": "12:00",
      "endtime": "2:00",
      "color": "#EF44EF",
      "url": ""
    }
  ]
}
'
Also as you can see in the example, the time formats aren't in seconds. They must be in a "YYYY-M-D" format for the date and a "H:mm" format for the time. Try the following and see if that helps.

**Comment by LinkBenjamin** [comment]
Yeah, I got it working.  I missed the wrapper object.  I had tried both styles of formatting the times and neither worked... but after I got the wrapper object in place I'm good.  Thanks!
