### ISSUE TITLE
How to load a specific date on page load instead of today's date?

### ISSUE THREAD

**Issue by hoa-ho** [kthornbloom/Monthly#42]
Hello,

First, I love this calendar. Thank you for your awesome work!

**My question is:**

When the page finish loading, I don't want it to automatically select today's date. I want it to read an already set date from an html element, then select that specific date in the calendar. 

**My js code:**
$('#mycalendar').monthly({
        mode: 'picker',
        // The element that will have its value set to the date you picked
        target: '#getDateSelected',
        // Add a style to days in the past
        stylePast: true,
        // Disable clicking days in the past
        disablePast: true
 });

Is there a js variable to load a specific date on page load?

Thanks!

**Comment by kthornbloom** [comment]
Sorry, there currently is not a great built-in option for this. If you are only using this plugin for this one calendar you are describing, you could edit the JS file to do what you want. Line 315 is where it sets the calendar to the current month and year:

`setMonthly(currentMonth, currentYear);`

You could get those values from an element on your page, and pass them in instead like:

```
var getMonth = $('.month-input').html(),
    getYear = $('.year-input').html();

setMonthly(getMonth, getYear);
```

Just keep in mind that anywhere you use this plugin, it will now be setting the calendar to that date.

**Comment by devlinhaines01** [comment]
I'm a beginner with JS, but try this maybe: 
$('#mycalendar').monthly({
	...
}, new Date('01 July 2017'));

And in monthly.js change line 7 to:
monthly: function(options, customDate) {

and change line 33 to 36 to:
currentMonth = customDate.getMonth() + 1,
currentYear = customDate.getFullYear(),
currentDay = customDate.getDate(),

**Comment by hoa-ho** [comment]
@devlinhaines01 Thanks man! It works!
