### ISSUE TITLE
Calendar does not load in IE 10

### ISSUE THREAD

**Issue by belljr56** [kthornbloom/Monthly#46]
I noticed there is a script error that is preventing the application from loading onto the page in Internet Explorer 10.

SCRIPT5007: Unable to get property 'toLowerCase' of undefined or null reference 
monthly.js, line 37 character 5

Do you intend to fix this error? It is happening on the demo site you have set up as well as with my own implementation of the code.

This seems to be an internet explorer only issue as the calendar is working exceptionally for me in all other browsers.

**Comment by kthornbloom** [comment]
Thank you for the report! I'll take a look

**Comment by richardtallent** [comment]
Apparently IE < 11 doesn't support navigator.language, have to use navigator.browserLanguage. I submitted a PR to fix.

**Comment by belljr56** [comment]
Thanks for the quick turn around, I was able to implement the fix that @richardtallent came up with and it works great!
