### ISSUE TITLE
Upon click on "Today" button whilst event list is shown calendar resets to current month with empty event list

### ISSUE THREAD

**Issue by andriikhmelkov** [kthornbloom/Monthly#62]
Steps:
1. Select any other month than current.
2. Click on any day to review list of events.
3. Click on "Today" button.

Expected:
- List of events shown for current month.

Actual:
- Empty events list shown for current month.

I were able to fix it for myself by adding `&& $(parent + " .monthly-event-list").hide()` to the following (hides events list):
```
// Reset button
$(parent + " .monthly-header-title").html(
	'<a href="#" class="monthly-header-title-date" onclick="return false">' + monthNames[month - 1] + " " + year + "</a>" + (settingCurrentMonth && $(parent + " .monthly-event-list").hide() ? "" : '<a href="#" class="monthly-reset"></a>'));
```

**Comment by kthornbloom** [comment]
Fixed (finally!)
