### ISSUE TITLE
Display Multiple Months

### ISSUE THREAD

**Issue by belljr56** [kthornbloom/Monthly#64]
Hello,

I am trying to utilize Monthly.js to display 3 months at a time (the current one as a large calendar and the next two as small previews). I was easily able to initiate 3 separate calendars using different IDs, however I am struggling to figure out how to make them show different months.

Is there a way to tell a calendar what month to load as? also is there a way to easily synch the next month button to trigger all three calendars that are displayed to change?

Thanks for any help,
Justin

**Comment by kthornbloom** [comment]
Hey Justin, the short answer is no, that kind of functionality is not built in however you could probably modify the plugin without _too_ much trouble. 

Check out line 83 for where it sets the initial month. You might be able to do some "if" statements and increment/deincrement the month for other specific calendars based on its ID.
