### ISSUE TITLE
how to add events to the calendar ?

### ISSUE THREAD

**Issue by krishnapreejith** [kthornbloom/Monthly#71]

**Comment by kthornbloom** [comment]
https://github.com/kthornbloom/Monthly/wiki/Events

**Comment by krishnapreejith** [comment]
Thanks for your reply sir, but I am actually asking to you that how we can
add events to the calendar in a user-friendly way. So that we can integrate
the calendar in our website and a user can add events manually in it (like
we all usually done in mobile calendar). hope you reply soon

Thanks in advance

**Comment by kthornbloom** [comment]
Hello,

    This plugin only covers displaying events on a calendar. To add the events, you'd need to use a form and the backend language of your choice to update the events XML file. Since there are so many ways that could be done, it is left up to you.

**Comment by arieljake** [comment]
I think he is asking about how to programmatically call addEvent. You don't seem to be returning the monthly instance when the plugin is run on a node.

**Comment by krishnapreejith** [comment]
Thank you for spending your valuable time for me...I used php to update xml
file and got it.

On Sat, Oct 28, 2017 at 12:44 AM, Ariel Jakobovits <notifications@github.com
