### ISSUE TITLE
Event Descriptions

### ISSUE THREAD

**Issue by drewsheneman** [kthornbloom/Monthly#77]
Is there a field or accepted way to handle event descriptions? I am currently appending them into the "name" field along with the Event Title:  "<name>Event Title - Event Description</name>".

**Comment by kthornbloom** [comment]
Hey there. My original thought was that you would use the URL field to link
to a new page that contains the event details. Because of that, I didn't
include much for displaying descriptions within the calendar

**Comment by drewsheneman** [comment]
Sounds good. Thanks for getting back to me.
