### ISSUE TITLE
Cant return to the month view

### ISSUE THREAD

**Issue by moodlesmedia** [kthornbloom/Monthly#9]
When i click on a date i can see the events, but i cant go back to the month view.

**Comment by kthornbloom** [comment]
Hi there. Could you provide a little more info?

- What browser & browser version?
- What device?
- Do you have this problem on the [demo page](http://kthornbloom.com/monthly/) as well?

**Comment by moodlesmedia** [comment]
He Kevin,

Sorry it was my fault. I did not see the calender icon next to the month name.
Maybe it a idea to place a return (font awesome: redo) button above the events to return.

Now i must search more then 5 minuten before i knew how to go back.
The plugin is awesome!

Martijn

**Comment by kthornbloom** [comment]
Thanks for the feedback! I'll think about how to make that more visible
