### ISSUE TITLE
Link to live demo invalid and possibly malicious

### ISSUE THREAD

**Issue by patrickatwsrn** [kthornbloom/Monthly#96]
The domain doesn't seem to have a proper ownder now. On top of this opening it sometimes forwards the visitor to a page containing malicious code.

http://kthornbloom.com/monthly

Please fix or remove the link as soon as possible.

P.S. Thanks for sharing your work here.

**Comment by kthornbloom** [comment]
Hey thanks for the heads up... let the domain lapse 🤦 . Removed the link for now.
